import './style.css'
import { mails, documents, users, logs } from './js/data.js'
import { icon, escapeHTML as esc, chart, stats } from './js/ui.js'

const app = document.querySelector('#app')
const state = { view: 'dashboard', mailTab: 'Bandeja de entrada', reportTab: 'Resumen', settingsTab: 'Mi perfil', profile: 'Pedro Chic', email:'pedro@empresa.com', messages: [], history: 'Resumen de contratos' }
const nav = [['dashboard','Inicio','home'],['chat','Asistente IA','spark'],['mail','Correos','mail'],['documents','Documentos','file'],['reports','Reportes','chart'],['analytics','Analítica','activity'],['users','Usuarios','users'],['logs','Bitácora','clock'],['settings','Configuración','settings']]
const today = new Date().toLocaleDateString('sv-SE')
let theme = 'light'
try { theme = localStorage.getItem('diali-theme') || 'light' } catch {}
document.documentElement.dataset.theme = theme
const button = (text, action, symbol = '', cls = 'primary') => `<button type="button" class="${cls}" data-action="${action}">${symbol ? icon(symbol) : ''}${text}</button>`
const badge = (text, color = 'blue') => `<span class="badge ${color}">${esc(text)}</span>`
function toast(text) { const el = document.querySelector('#toast'); el.textContent = text; el.classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('visible'), 3800) }
function login() {
  app.innerHTML = `<div class="login"><section class="login-brand"><div class="brand">${icon('spark')}<span>Diali <b>IA</b></span></div><div class="login-story"><span class="eyebrow">INTELIGENCIA QUE CONECTA</span><h1>Tu información.<br>Todo su potencial.</h1><p>Sistema Inteligente Multimodal de Optimización y Asistencia Operativa Corporativa</p><div class="orbit"><div class="orbit-core">${icon('spark')}<strong>Diali IA</strong></div><span class="orbit-item o1">${icon('mail')} Correos</span><span class="orbit-item o2">${icon('file')} Documentos</span><span class="orbit-item o3">${icon('spark')} Chat IA</span><span class="orbit-item o4">${icon('chart')} Analítica</span></div></div><p class="tagline">Información en acción, decisiones con inteligencia</p></section><section class="login-form"><div class="login-box"><span class="badge blue">TU ESPACIO DE TRABAJO</span><h2>Bienvenido de nuevo</h2><p>Inicia sesión para conectar con lo que importa.</p><form id="login-form"><label>Correo institucional<input name="email" type="email" placeholder="usuario@empresa.com" required autocomplete="username"></label><label>Contraseña<input name="password" type="password" placeholder="Ingresa tu contraseña" required autocomplete="current-password"></label><div class="form-between"><label class="check"><input name="remember" type="checkbox"> Recordarme</label><button type="button" class="text-button" data-action="forgot">¿Olvidaste tu contraseña?</button></div><button class="primary full" type="submit">Iniciar sesión ${icon('arrow')}</button></form><div class="divider">o continúa con</div>${button('<span class="microsoft">▦</span> Iniciar con Microsoft','microsoft','','secondary full')}<p class="demo-note">${icon('shield')} Entorno de demostración. Usa cualquier correo y contraseña de prueba.</p></div><small>© ${new Date().getFullYear()} Diali IA · Inteligencia para tu empresa</small></section></div><div id="toast" role="status"></div><dialog id="modal" aria-label="Ventana de diálogo"></dialog>`
  try { document.querySelector('[name=email]').value = localStorage.getItem('diali-email') || '' } catch {}
}
function shell() {
 app.innerHTML = `<div class="workspace"><button class="scrim" data-action="menu" aria-label="Cerrar menú"></button><aside class="sidebar"><div class="brand">${icon('spark')}<span>Diali <b>IA</b></span></div><div class="workspace-label">WORKSPACE CORPORATIVO</div><nav aria-label="Navegación principal">${nav.map(([key,label,symbol]) => `<button data-view="${key}" title="${label}" aria-label="${label}">${icon(symbol)}<span>${label}</span>${key==='mail'?'<small>12</small>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="connection"><span></span><span>Sistema conectado<small>Servicios de demostración</small></span></div><button data-action="logout" aria-label="Cerrar sesión">${icon('logout')}<span>Cerrar sesión</span></button></div></aside><div class="main"><header><div class="header-left"><button class="icon-button mobile-menu" data-action="menu" aria-label="Abrir menú">${icon('menu')}</button><span id="module-title"></span></div><div class="header-right"><span class="date">${new Intl.DateTimeFormat('es-GT',{day:'numeric',month:'long',year:'numeric'}).format(new Date())}</span><button class="icon-button" data-action="theme" aria-label="Cambiar tema">${icon('moon')}</button><button class="icon-button notification" data-action="notifications" aria-label="Ver notificaciones">${icon('bell')}</button><button class="account" data-view="settings"><span class="avatar">PC</span><span><strong class="profile-name">${esc(state.profile)}</strong><small>Administrador</small></span></button></div></header><main id="content"></main><footer>Diali IA · Asistencia operativa inteligente<span>Entorno de demostración</span></footer></div></div><div id="toast" role="status"></div><dialog id="modal" aria-label="Ventana de diálogo"></dialog>`
 navigate(state.view)
}
function heading(title, subtitle, action = '') { return `<div class="page-heading"><div><span class="eyebrow">DIALI IA / ESPACIO DE TRABAJO</span><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>` }
function dashboard() { return `${heading(`Hola, ${esc(state.profile.split(' ')[0])} <span class="hello">✦</span>`, 'Aquí tienes un resumen de la actividad de hoy.', '<span class="live">● Actualizado ahora</span>')}${stats([['Correos pendientes','125','mail','12 nuevos hoy'],['Documentos procesados','1,430','file','↑ 18.6% este mes'],['Consultas IA','854','spark','↑ 24.3% este mes'],['Alertas','7','bell','3 requieren atención']])}<div class="dashboard-grid"><section class="card"><div class="card-heading"><div><h2>Actividad reciente</h2><p>Tu operación, en una sola mirada</p></div><span class="badge neutral">Últimos 7 días</span></div>${chart()}<div class="legend"><span><i></i>Correos</span><span><i class="cyan"></i>Documentos</span><span><i class="purple"></i>Consultas IA</span></div></section><section class="card quick"><h2>Acciones rápidas</h2><p>Menos pasos, más resultados</p>${[['Nuevo correo','compose','mail'],['Subir documento','upload','file'],['Consultar con IA','go-chat','spark'],['Generar reporte','report','chart'],['Configurar alertas','alerts','bell']].map(([label,action,symbol])=>button(`${label}<span class="push">↗</span>`,action,symbol,'quick-button')).join('')}</section><section class="card recent"><div class="card-heading"><h2>Últimos movimientos</h2><button class="text-button" data-view="logs">Ver bitácora →</button></div>${logs.slice(0,3).map((l,i)=>`<div class="activity-row"><span class="metric-icon">${icon(['shield','file','mail'][i])}</span><div><strong>${esc(l.description)}</strong><p>${esc(l.user)} · ${l.time}</p></div>${badge('Completado','green')}</div>`).join('')}</section><section class="assistant-card"><span class="assistant-symbol">${icon('spark')}</span><span class="eyebrow">TU ALIADO INTELIGENTE</span><h2>Diali IA está listo para ayudarte</h2><p>Transforma documentos, correos y preguntas en respuestas útiles.</p>${button('Abrir asistente →','go-chat','','white')}</section></div>` }
function chat() { return `${heading('Asistente IA','Tu aliado inteligente para información y procesos.')}<div class="chat-layout card"><aside class="chat-history">${button('Nueva conversación','new-chat','plus','secondary full')}<span class="eyebrow">CONVERSACIONES RECIENTES</span>${['Resumen de contratos','Análisis financiero Q2','Políticas de la empresa','Reporte de ventas','Procedimiento de compras'].map(t=>`<button class="history-item ${state.history===t?'selected':''}" data-history="${t}">${icon('chat')}${t}</button>`).join('')}<div class="chat-disclaimer">${icon('shield')} Respuestas simuladas para este prototipo.</div></aside><section class="chat-main"><div class="chat-top"><span class="metric-icon">${icon('spark')}</span><div><strong>Diali IA</strong><small><span class="status-dot"></span> Disponible para ayudarte</small></div></div><div id="messages" class="messages" aria-live="polite">${state.messages.length ? state.messages.map(messageHTML).join('') : initialChat()}</div><form id="chat-form" class="chat-compose"><label class="sr-only" for="chat-input">Escribe tu consulta</label><textarea id="chat-input" name="message" placeholder="Escribe tu consulta..." rows="2" required></textarea><div><input id="chat-file" type="file" hidden><button type="button" class="text-button" data-action="attach">${icon('file')} Adjuntar</button><button type="button" class="icon-button" data-action="microphone" aria-label="Micrófono">${icon('mic')}</button><button class="primary" type="submit">Enviar ${icon('arrow')}</button></div></form><small class="chat-foot">Diali IA puede cometer errores. Revisa la información importante.</small></section></div>` }
function initialChat() { return `<div class="message user">¿Puedes darme un resumen del contrato adjunto y los puntos más importantes?</div><div class="message ai"><span class="ai-label">✦ DIALI IA</span><p>Claro, aquí tienes un resumen del documento:</p><div class="contract-grid"><div><small>Tipo</small>Contrato de servicio</div><div><small>Vigencia</small>01/01/2026 - 31/12/2026</div><div><small>Monto</small>Q150,000</div><div><small>Partes</small>Empresa XYZ y Servicios S.A.</div></div><p><strong>Puntos clave:</strong> Confidencialidad, SLA y penalizaciones.</p><div class="file-card">${icon('file')}<span>contrato_servicio.pdf<small>Documento de ejemplo · PDF</small></span>${button('Analizar documento','analyze','','secondary')}</div><small>Respuesta simulada · Basada en datos de ejemplo</small></div>` }
function messageHTML(m) { return `<div class="message ${m.role}">${m.role==='ai'?'<span class="ai-label">✦ DIALI IA</span>':''}<p>${esc(m.text)}</p></div>` }
const tabs = (items, active, type) => `<div class="tabs" role="tablist">${items.map(t=>`<button role="tab" aria-selected="${active===t}" class="${active===t?'active':''}" data-tab="${type}" data-value="${t}">${t}</button>`).join('')}</div>`
const search = placeholder => `<div class="search">${icon('search')}<input id="search" aria-label="${placeholder}" placeholder="${placeholder}"></div>`
const select = (id, options) => `<select id="${id}" aria-label="${options[0]}">${options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`
const table = headers => `<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody id="table-body"></tbody></table></div><div class="table-footer"><span id="result-count"></span><span>Datos de demostración</span></div>`
function mailView() { return `${heading('Correos','Organiza tu comunicación con inteligencia.',button('Redactar','compose','plus'))}<section class="card table-card">${tabs(['Bandeja de entrada','Enviados','Clasificados','Importantes'],state.mailTab,'mail')}<div class="toolbar">${search('Buscar correos...')}<span class="badge green">✦ Clasificación inteligente activa</span></div>${table(['Remitente','Asunto','Hora / Fecha','Categoría'])}</section>` }
function documentsView() { return `${heading('Documentos','Todo el conocimiento de tu empresa, en un solo lugar.',button('Subir documento','upload','plus'))}<section class="card table-card"><div class="toolbar">${search('Buscar documentos...')}${select('type-filter',['Todos los tipos','PDF','Excel','Word'])}<label class="date-filter">Fecha <input id="date-filter" type="date"></label></div>${table(['Nombre','Tipo','Fecha','Estado','Acciones'])}</section>` }
function usersView() { return `${heading('Usuarios','Administración de usuarios del sistema',button('Nuevo usuario','new-user','plus'))}<section class="card table-card"><div class="toolbar">${search('Buscar usuarios...')}${select('role-filter',['Todos los roles','Administrador','Analista','Soporte','Gerente','Finanzas'])}</div>${table(['Nombre','Correo','Rol','Estado','Acciones'])}</section>` }
function logsView() { return `${heading('Bitácora de actividades','Registro de acciones en el sistema')}<section class="card table-card"><div class="toolbar">${search('Buscar en bitácora')}${select('user-filter',['Todos los usuarios',...new Set(logs.map(l=>l.user))])}${select('action-filter',['Todas las acciones',...new Set(logs.map(l=>l.action))])}<label class="date-filter">Fecha <input type="date" id="date-filter"></label></div>${table(['Fecha y hora','Usuario','Acción','Descripción','IP'])}</section>` }
function reportsView() { const summary=state.reportTab==='Resumen';const labels=summary?['Correos','Documentos','IA','Reportes']:['Semana 1','Semana 2','Semana 3','Semana 4'];const values=summary?[4320,1430,854,320]:({'Correos':[890,1040,1110,1280],'Documentos':[280,320,390,440],'Financiero':[28000,35000,41000,46000],'Uso de IA':[160,194,220,280]}[state.reportTab]);return `${heading('Reportes y Analítica','Convierte la actividad de tu equipo en mejores decisiones.',button('Exportar reporte','report','download'))}${tabs(['Resumen','Correos','Documentos','Financiero','Uso de IA'],state.reportTab,'reports')}${stats([['Correos procesados','4,320','mail','↑ 12.8% este mes'],['Documentos analizados','1,430','file','↑ 18.6% este mes'],['Consultas IA','854','spark','↑ 24.3% este mes'],['Alertas generadas','25','bell','Este mes']])}<div class="reports-grid"><section class="card"><div class="card-heading"><div><h2>${summary?'Actividad por módulo':`Actividad · ${state.reportTab}`}</h2><p>${state.reportTab==='Financiero'?'Montos en quetzales':'Distribución del período'} · Datos simulados</p></div>${badge('Septiembre 2026')}</div><div class="bar-chart" role="img" aria-label="${labels.map((l,i)=>`${l}: ${values[i]}`).join(', ')}">${labels.map((l,i)=>`<div class="bar-column"><strong>${values[i].toLocaleString('en-US')}</strong><div class="bar" style="--height:${values[i]/Math.max(...values)*80}%;--bar-color:${['#0b63f6','#3ea6ff','#8b7cf8','#70d3cb'][i]}"></div><small>${l}</small></div>`).join('')}</div></section><section class="card"><h2>Tipos de documentos</h2><p>Composición de tu biblioteca</p><div class="donut" role="img" aria-label="Contratos 35%, Facturas 25%, Reportes 20%, Otros 20%"><div><strong>1,430</strong><small>documentos</small></div></div><div class="donut-legend">${['Contratos','Facturas','Reportes','Otros'].map((t,i)=>`<div><i style="background:${['#0b63f6','#3ea6ff','#8b7cf8','#c9d6e8'][i]}"></i>${t}<strong>${[35,25,20,20][i]}%</strong></div>`).join('')}</div></section></div><div class="insight">${icon('spark')}<div><strong>Una operación cada vez más inteligente</strong><p>Las consultas de IA aumentaron un 24.3% este mes. Explora cómo tu equipo aprovecha la información.</p></div></div>` }
function settings() { return `${heading('Configuración','Personaliza tu experiencia en Diali IA.')}<section class="card settings-card">${tabs(['Mi perfil','Seguridad','Notificaciones','Integraciones'],state.settingsTab,'settings')}<form id="settings-form">${state.settingsTab==='Mi perfil'?`<div class="profile-banner"><span class="avatar large">PC</span><div><h2>${esc(state.profile)}</h2><p>Administrador · Cuenta corporativa</p></div>${badge('Activo','green')}</div><div class="form-grid"><label>Nombre<input name="name" value="${esc(state.profile)}" required></label><label>Correo<input name="email" value="${esc(state.email)}" type="email" required></label><label>Rol<input value="Administrador" disabled></label><label>Idioma<select><option>Español</option></select></label><label>Tema<select id="theme-select"><option value="light" ${theme==='light'?'selected':''}>Claro</option><option value="dark" ${theme==='dark'?'selected':''}>Oscuro</option></select></label></div><h3>Preferencias</h3>${toggles()}`:state.settingsTab==='Seguridad'?`<h2>Seguridad de la cuenta</h2><p>Este prototipo no almacena contraseñas ni modifica credenciales reales.</p><label>Nueva contraseña de prueba<input name="newPassword" type="password" minlength="8" required autocomplete="new-password"></label><label>Confirmar contraseña<input name="confirmPassword" type="password" minlength="8" required autocomplete="new-password"></label>`:state.settingsTab==='Notificaciones'?`<h2>Notificaciones</h2><p>Elige las novedades que quieres recibir.</p>${toggles()}`:`<h2>Integraciones</h2><p>Conexiones de ejemplo; no se utilizan APIs reales.</p><div class="integration">${icon('mail')}<div><strong>Microsoft 365</strong><p>Correo y documentos corporativos</p></div>${badge('Simulado')}</div><div class="integration">${icon('spark')}<div><strong>Motor de Diali IA</strong><p>Asistencia con respuestas de demostración</p></div>${badge('Demo','green')}</div>`}<div class="form-actions"><span>Los cambios se aplican a esta demostración.</span><button class="primary" type="submit">Guardar cambios</button></div></form></section>` }
const preferences = { 'Notificaciones por correo':true, 'Alertas en el sistema':true, 'Resumen diario':false }
function toggles() { return Object.entries(preferences).map(([t,on])=>`<label class="toggle-row"><span>${t}</span><input type="checkbox" name="${t}" role="switch" ${on?'checked':''}><span class="switch"></span></label>`).join('') }
function navigate(view) { state.view = nav.some(n=>n[0]===view)?view:'dashboard'; document.querySelector('.workspace').classList.remove('menu-open'); document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===state.view); if(el.closest('nav')) el.setAttribute('aria-current',el.dataset.view===state.view?'page':'false')}); document.querySelector('#module-title').textContent = nav.find(n=>n[0]===state.view)[1]; document.querySelector('#content').innerHTML = ({dashboard,chat,mail:mailView,documents:documentsView,reports:reportsView,analytics:reportsView,users:usersView,logs:logsView,settings}[state.view])(); renderTable(); window.scrollTo(0,0) }
function renderTable() {
 const body = document.querySelector('#table-body'); if(!body) return
 const value = id => document.getElementById(id)?.value || ''
 const q = value('search').toLocaleLowerCase('es'); let rows=[]
 if(state.view==='mail') rows=mails.filter(m=>(state.mailTab==='Enviados'?m.sent:!m.sent)&&(state.mailTab!=='Importantes'||m.important)&&(state.mailTab!=='Clasificados'||m.category)).filter(m=>Object.values(m).join(' ').toLowerCase().includes(q)).map(m=>`<td><span class="mail-avatar">${esc(m.sender[0].toUpperCase())}</span>${esc(m.sender)}</td><td><button class="table-link" data-mail="${m.id}">${esc(m.subject)}</button>${m.important?'<span class="star"> ★</span>':''}</td><td>${m.time}</td><td>${badge(m.category,m.color)}</td>`)
 if(state.view==='documents') rows=documents.filter(d=>d.name.toLowerCase().includes(q)&&(!value('type-filter')||value('type-filter')==='Todos los tipos'||d.type===value('type-filter'))&&(!value('date-filter')||d.date===value('date-filter'))).map(d=>`<td><span class="doc-icon">${icon('file')}</span><strong>${esc(d.name)}</strong></td><td>${badge(d.type,'neutral')}</td><td>${d.date}</td><td>${badge('Procesado','green')}</td><td><div class="row-actions"><button title="Ver" aria-label="Ver ${esc(d.name)}" data-doc="${d.id}" data-operation="view">${icon('eye')}</button><button title="Descargar" aria-label="Descargar ${esc(d.name)}" data-doc="${d.id}" data-operation="download">${icon('download')}</button><button title="Analizar con IA" aria-label="Analizar ${esc(d.name)} con IA" data-doc="${d.id}" data-operation="analyze">${icon('spark')}</button></div></td>`)
 if(state.view==='users') rows=users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(q)&&(value('role-filter')==='Todos los roles'||u.role===value('role-filter'))).map(u=>`<td><span class="mail-avatar">${esc(u.name.split(' ').map(n=>n[0]).join(''))}</span><strong>${esc(u.name)}</strong></td><td>${esc(u.email)}</td><td>${badge(u.role,'neutral')}</td><td>${badge(u.active?'Activo':'Inactivo',u.active?'green':'neutral')}</td><td><div class="row-actions"><button data-edit-user="${u.id}" aria-label="Editar ${esc(u.name)}">${icon('edit')}</button><button data-toggle-user="${u.id}" aria-label="${u.active?'Desactivar':'Activar'} ${esc(u.name)}">${icon('power')}</button></div></td>`)
 if(state.view==='logs') rows=logs.filter(l=>Object.values(l).join(' ').toLowerCase().includes(q)&&(value('user-filter')==='Todos los usuarios'||l.user===value('user-filter'))&&(value('action-filter')==='Todas las acciones'||l.action===value('action-filter'))&&(!value('date-filter')||l.date===value('date-filter'))).map(l=>`<td>${l.date}<small>${l.time}</small></td><td>${esc(l.user)}</td><td>${badge(l.action)}</td><td>${esc(l.description)}</td><td><code>${l.ip}</code></td>`)
 body.innerHTML=rows.length?rows.map(r=>`<tr>${r}</tr>`).join(''):`<tr><td colspan="6" class="empty">${icon('search')}No se encontraron resultados. Prueba con otros filtros.</td></tr>`; document.querySelector('#result-count').textContent=`${rows.length} registros`
}
function log(action,description) { logs.unshift({date:today,time:new Date().toLocaleTimeString('es-GT',{hour:'2-digit',minute:'2-digit'}),user:state.profile,action,description,ip:'192.168.1.10'}) }
let previousFocus
function modal(title,body,submit='',id='modal-form') { previousFocus=document.activeElement; const el=document.querySelector('#modal'); el.innerHTML=`<div class="modal-heading"><h2 id="modal-title">${title}</h2><button type="button" class="icon-button" data-action="close-modal" aria-label="Cerrar">${icon('close')}</button></div><form id="${id}">${body}<div class="modal-actions">${button(submit?'Cancelar':'Cerrar','close-modal','','secondary')}${submit?`<button type="submit" class="primary">${submit}</button>`:''}</div></form>`;el.setAttribute('aria-labelledby','modal-title');el.showModal(); el.addEventListener('close',()=>previousFocus?.focus(),{once:true}) }
function uploadModal() { modal('Subir documento',`<div class="upload-zone">${icon('file')}<strong>Agrega conocimiento a tu espacio</strong><p>El archivo permanece en este navegador.</p><label>Seleccionar archivo<input name="file" type="file" accept=".pdf,.xlsx,.xls,.doc,.docx" required></label></div><label>Tipo de documento<select name="kind"><option>Contrato</option><option>Factura</option><option>Reporte</option><option>Otro</option></select></label><label>Descripción<textarea name="description" rows="3" placeholder="Describe brevemente el documento"></textarea></label>`,'Subir','upload-form') }
function userModal(id) { const u=users.find(u=>u.id===Number(id)); modal(u?'Editar usuario':'Nuevo usuario',`<input type="hidden" name="id" value="${u?.id||''}"><label>Nombre<input name="name" required value="${esc(u?.name||'')}"></label><label>Correo<input name="email" type="email" required value="${esc(u?.email||'')}"></label><label>Rol<select name="role">${['Administrador','Analista','Soporte','Gerente','Finanzas'].map(r=>`<option ${u?.role===r?'selected':''}>${r}</option>`).join('')}</select></label>`,'Guardar','user-form') }
function download(name,content,type='text/plain') { const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type})); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000) }
function setTheme(next) { theme=next; document.documentElement.dataset.theme=theme; try {localStorage.setItem('diali-theme',theme)} catch {} }
document.addEventListener('click',e=>{
 const target=e.target.closest('button'); if(!target)return
 if(target.dataset.view){navigate(target.dataset.view);return}
 if(target.dataset.tab){state[{mail:'mailTab',reports:'reportTab',settings:'settingsTab'}[target.dataset.tab]]=target.dataset.value;navigate(state.view);return}
 if(target.dataset.history){state.history=target.dataset.history;state.messages=state.history==='Resumen de contratos'?[]:[{role:'ai',text:`Conversación de ejemplo: ${state.history}. Puedo ayudarte a explorar este tema con datos simulados.`}];navigate('chat');return}
 if(target.dataset.editUser){userModal(target.dataset.editUser);return}
 if(target.dataset.toggleUser){const u=users.find(u=>u.id===Number(target.dataset.toggleUser));u.active=!u.active;log('USUARIO',`${u.active?'Activó':'Desactivó'} a ${u.name}`);renderTable();toast('Estado del usuario actualizado');return}
 if(target.dataset.mail){const m=mails.find(m=>m.id===Number(target.dataset.mail));modal(esc(m.subject),`<p><strong>${esc(m.sender)}</strong> · ${m.time}</p>${badge(m.category)}<p class="mail-body">${esc(m.body||'Hola, compartimos esta información para tu revisión. Agradecemos tu seguimiento y quedamos atentos a tus comentarios. Este es un correo de demostración.')}</p>`);return}
 if(target.dataset.doc){const d=documents.find(d=>d.id===Number(target.dataset.doc));if(target.dataset.operation==='download'){download(d.file?d.name:`${d.name}.demo.txt`,d.file||`Documento de demostración: ${d.name}\nNo contiene un archivo real.`);toast(d.file?'Archivo descargado':'Ficha de ejemplo descargada')}else if(target.dataset.operation==='analyze'){state.messages=[{role:'user',text:`Analiza ${d.name}`},{role:'ai',text:`Análisis simulado de ${d.name}: documento clasificado como ${d.kind||d.type} y marcado como procesado. En este prototipo no se extrae ni se interpreta el contenido real.`}];navigate('chat')}else modal('Detalle del documento',`<div class="file-card">${icon('file')}<strong>${esc(d.name)}</strong></div><p>Tipo: ${d.type} · Fecha: ${d.date}</p><p>${esc(d.description||'Documento de ejemplo de la biblioteca corporativa.')}</p>${badge('Procesado','green')}<p>Vista de metadatos. La previsualización del contenido no está disponible en esta demostración.</p>`);return}
 const actions={menu:()=>document.querySelector('.workspace').classList.toggle('menu-open'),logout:()=>{state.view='dashboard';login()},theme:()=>{setTheme(theme==='light'?'dark':'light');const s=document.querySelector('#theme-select');if(s)s.value=theme},notifications:()=>modal('Notificaciones',`<p>${badge('7 alertas','orange')}</p><p>3 documentos requieren revisión.</p><p>2 correos están marcados como importantes.</p><p>2 reportes están disponibles.</p>`),forgot:()=>modal('Recuperar acceso','<p>Esta es una demostración sin autenticación real. Puedes iniciar sesión con cualquier correo válido y una contraseña de prueba.</p>'),microsoft:()=>{log('LOGIN','Inicio de sesión simulado con Microsoft');shell();toast('Sesión Microsoft simulada')},'go-chat':()=>navigate('chat'),upload:uploadModal,'new-user':()=>userModal(),alerts:()=>{state.settingsTab='Notificaciones';navigate('settings')},'close-modal':()=>document.querySelector('#modal').close(),compose:()=>modal('Redactar correo','<label>Para<input type="email" name="to" required placeholder="destinatario@empresa.com"></label><label>Asunto<input name="subject" required></label><label>Mensaje<textarea name="body" rows="5" required></textarea></label><p class="demo-note">Envío simulado. No se enviará ningún correo real.</p>','Enviar','compose-form'),report:()=>{download('Diali_reporte.csv','Módulo,Total\nCorreos,4320\nDocumentos,1430\nConsultas IA,854\nAlertas,25','text/csv;charset=utf-8');log('REPORTE','Generó un reporte');toast('Reporte de demostración descargado')},'new-chat':()=>{state.history='';state.messages=[{role:'ai',text:'Hola, soy Diali IA. ¿En qué puedo ayudarte hoy? Las respuestas de esta conversación son simuladas.'}];navigate('chat')},attach:()=>document.querySelector('#chat-file').click(),microphone:()=>toast('Micrófono de demostración. Escribe tu consulta para continuar.'),analyze:()=>{state.messages=[{role:'ai',text:'Análisis simulado: contrato de servicio por Q150,000, vigente del 01/01/2026 al 31/12/2026. Revisa las cláusulas de confidencialidad, SLA y penalizaciones.'}];navigate('chat')}}
 actions[target.dataset.action]?.()
})
document.addEventListener('input',e=>{if(e.target.id==='search')renderTable()})
document.addEventListener('change',e=>{if(e.target.id.endsWith('-filter'))renderTable();if(e.target.id==='theme-select')setTheme(e.target.value);if(e.target.id==='chat-file'&&e.target.files[0]){document.querySelector('#chat-input').value=`Analiza el archivo ${e.target.files[0].name}`;toast('Archivo seleccionado para análisis simulado')}})
document.addEventListener('keydown',e=>{if(e.target.id==='chat-input'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.target.form.requestSubmit()}})
document.addEventListener('submit',e=>{
 e.preventDefault();const form=e.target;const data=new FormData(form)
 if(form.id==='login-form'){try{if(data.has('remember'))localStorage.setItem('diali-email',data.get('email'));else localStorage.removeItem('diali-email')}catch{}log('LOGIN','Inicio de sesión');shell()}
 if(form.id==='chat-form'){const text=data.get('message').trim();if(!text)return;if(!state.messages.length)state.messages=[{role:'user',text:'¿Puedes darme un resumen del contrato adjunto y los puntos más importantes?'},{role:'ai',text:'Contrato de servicio · 01/01/2026 - 31/12/2026 · Q150,000 · Empresa XYZ y Servicios S.A. Puntos clave: confidencialidad, SLA y penalizaciones.'}];state.messages.push({role:'user',text},{role:'ai',text:'He recibido tu consulta. En esta demostración puedo mostrar resúmenes y datos de ejemplo. Para este caso, te sugiero revisar los documentos relacionados, identificar los compromisos pendientes y priorizar las acciones con tu equipo. Esta respuesta es simulada.'});document.querySelector('#messages').innerHTML=state.messages.map(messageHTML).join('');form.reset();document.querySelector('#messages').scrollTop=document.querySelector('#messages').scrollHeight}
 if(form.id==='upload-form'){const file=data.get('file');const ext=file.name.split('.').pop().toLowerCase();if(!['pdf','xlsx','xls','doc','docx'].includes(ext)){toast('Selecciona un archivo PDF, Excel o Word');return}documents.unshift({id:Date.now(),name:file.name,type:ext==='pdf'?'PDF':ext.startsWith('xls')?'Excel':'Word',date:today,file,kind:data.get('kind'),description:data.get('description')});log('DOCUMENTO','Subió un documento');document.querySelector('#modal').close();navigate('documents');toast('Documento agregado localmente · Procesamiento simulado')}
 if(form.id==='user-form'){const id=Number(data.get('id'));if(users.some(u=>u.email.toLowerCase()===data.get('email').toLowerCase()&&u.id!==id)){toast('Ya existe un usuario con ese correo');return}const record={name:data.get('name').trim(),email:data.get('email'),role:data.get('role')};if(!record.name){toast('Ingresa un nombre válido');return}if(id)Object.assign(users.find(u=>u.id===id),record);else users.push({id:Date.now(),...record,active:true});log('USUARIO',id?'Editó un usuario':'Creó un usuario');document.querySelector('#modal').close();navigate('users');toast('Usuario guardado')}
 if(form.id==='compose-form'){mails.unshift({id:Date.now(),sender:data.get('to'),subject:data.get('subject'),body:data.get('body'),time:'Ahora',category:'Enviado',color:'blue',sent:true});log('CORREO','Envió un correo simulado');document.querySelector('#modal').close();state.mailTab='Enviados';navigate('mail');toast('Correo enviado en modo demostración')}
 if(form.id==='settings-form'){if(state.settingsTab==='Seguridad'&&data.get('newPassword')!==data.get('confirmPassword')){toast('Las contraseñas no coinciden');return}if(data.has('name')){state.profile=data.get('name').trim()||'Pedro Chic';state.email=data.get('email');document.querySelector('.profile-name').textContent=state.profile}if(['Mi perfil','Notificaciones'].includes(state.settingsTab))Object.keys(preferences).forEach(k=>preferences[k]=data.has(k));log('CONFIGURACIÓN','Actualizó parámetros');toast(state.settingsTab==='Seguridad'?'Validación simulada completada. No se guardó la contraseña.':'Cambios guardados en esta sesión');if(state.settingsTab==='Seguridad')form.reset()}
})
login()
